UaClient/ServiceModel/Ua/Channels/CommunicationObject.cs

This causes a [CS0414](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0414) warning.

There is no read access to the `closedCalled` variable -> remove it

---

UaClient/ServiceModel/Ua/DirectoryStore.cs

ValidateRemoteCertificateAsync does not use await, hence use `Task.FromResult` instead of `async`. This fixes a CS1998 warning.

ValidateRemoteCertificateAsync does not use await

---

.github/workflows/unittests.yml
UaClient.UnitTests/Workstation.UaClient.UnitTests.csproj
UaClient/Workstation.UaClient.csproj

This PR adds an github workflow that will automatically run the unit tests after a push to the repository and after a pull request. That way you always know that a change will not break compilation and one of the unit tests. Since the test run on a ubuntu machine, I had to change the unit tests to be a dotnet core library instead of .net framework. Futhermore I had to change the language from _default_ to _latest_. I guess on the test machine _default_ is interpreted as _latest major version_ (that is 7), but the code use 7.1 or 7.2 language features.
[Github actions](https://github.com/features/actions) are still in a semi public beta phase and will go public in November. So propbably the workflow will not run in your repository atm. You can of course, also sign up to participate on the …

Add a github workflow to automatically run the unit tests

---

UaClient.UnitTests/UnitTests/Channels/BinaryDecoderTests.Equivalency.cs
UaClient.UnitTests/UnitTests/Channels/BinaryDecoderTests.cs
UaClient/ServiceModel/Ua/Channels/BinaryDecoder.cs

This PR adds unit tests for the binary decoder in the same fashion as it is done in #99. In fact it is more or less a 1-to-1 copy where just the types and method names are exchanged. I found two cases that are not handled absolutely correctly.
1. The edge cases of DateTime are not handled. `DateTime.MinValue` will be decoded as the minimum value of the file time format (1600-01-01). Decoding `DateTime.MaxValue` will actually throw an exception.
2. An empty string is decoded as `null`.
I will commit fixes for both cases to this branch in a few minutes. Let me know if you prefer to have them in separated PRs.

Add binary decoder unit tests

---

UaClient.UnitTests/UnitTests/Channels/BinaryEncoderTests.Equivalency.cs
UaClient.UnitTests/UnitTests/Channels/BinaryEncoderTests.cs

When I initially wrote the tests for the binary encoder I stepwisely worked around the problems I faced. The main challenge was to test the equivalency of the `opc-ua-client` and of the `Opc.Ua` types. I found now a way to handle that globally with fluent assertions. That way the tests are now very uniform and I could easily add some more of them.

Rework the unit tests for the binary encoder

---

UaClient/Collections/ObservableQueue.cs
UaClient/ServiceModel/Ua/Channels/BinaryDecoder.cs
UaClient/ServiceModel/Ua/Channels/BinaryEncoder.cs
UaClient/ServiceModel/Ua/Channels/CommunicationObject.cs
UaClient/ServiceModel/Ua/Channels/UaTcpSessionChannel.cs
UaClient/ServiceModel/Ua/DirectoryStore.cs
UaClient/ServiceModel/Ua/MonitoredItemCollection.cs
UaClient/ServiceModel/Ua/SubscriptionBase.cs
UaClient/ServiceModel/Ua/Variant.cs

Here I add `readonly` to some private fields. This change should be safe as long as it compiles.

Use readonly when possible

---

UaClient.UnitTests/TestException.cs
UaClient.UnitTests/UnitTests/Channels/CommunicationObjectTests.cs

I tried to cover here many possible state transitions. The final state as well as the intermediate states (if possible) are tested. Also the call order is recorded and compared to the expectation. I have to admit, however, that I didn't tried to guess the correct order, but simply made the tests pass.

Add unit tests for the communication object

---

UaClient.UnitTests/UnitTests/Channels/BinaryDecoderTests.Equivalency.cs
UaClient.UnitTests/UnitTests/Channels/BinaryDecoderTests.cs
UaClient.UnitTests/UnitTests/Channels/BinaryEncoderTests.Equivalency.cs
UaClient.UnitTests/UnitTests/Channels/BinaryEncoderTests.cs

I finally got my hands on coverlet. This PR increase the overall code coverage of the unit tests from 34.2% to 37.2%. My medium-term plan is to reach 50%. After that it'll become more difficult. Once the low hanging fruits are picked, I'll open an issue to discuss how we can tackle the other half.
Btw: this time I found a bug in [FluentAssertions](https://github.com/fluentassertions/fluentassertions/issues/1167) :smile:.

Increase code coverage of the binary encoder and decoder tests

---

UaClient/ServiceModel/Ua/Channels/UaTcpSessionChannel.cs

When the OPC UA server does not have anonymous authentication enabled and no username and password are provided, you get the following error:
> System.ArgumentNullException: 'String reference not set to an instance of a String.
> Parameter name: s'
at line 592 of UaTcpSessionChannel.cs
```
var userNameIdentity = (UserNameIdentity)this.UserIdentity;
byte[] passwordBytes = System.Text.Encoding.UTF8.GetBytes(userNameIdentity.Password);
```
because the password is null.
This change throws an exception that is more clear. Let me know if I should change the Exception message or Exception class.
Thanks

exception when not anonymous and no user/pass

---

UaClient.UnitTests/UnitTests/LocalizedTextTests.cs
UaClient.UnitTests/UnitTests/NodeIdTests.cs
UaClient.UnitTests/UnitTests/QualifiedNameTests.cs
UaClient.UnitTests/Workstation.UaClient.UnitTests.csproj
UaClient.UnitTests/coverlet.runsettings
UaClient/ServiceModel/Ua/NodeId.cs

This PR increase the code and branch coverage to nearly 100% for `LocalizedText` (100%), `QualifiedName` (100%) and `NodeId` (98.5%/97.1%). One test is failing. The reason is that the `GetHashCode` method of the node ID
https://github.com/convertersystems/opc-ua-client/blob/a3b0a496233115ccd837bd1602fab17f8af657a8/UaClient/ServiceModel/Ua/NodeId.cs#L237-L242
The the hash code of the identifier is linked on the reference and not the value in the case of a byte array, so two sequential equal arrays have different hash codes.

Improve unit tests

---

UaClient.UnitTests/UnitTests/ErrorsContainerTests.cs
UaClient.UnitTests/UnitTests/ObservableQueueTests.cs
UaClient/Collections/ObservableQueue.cs

Some more tests. With that PR (and the other open PR) we are now on a code coverage ratio of 49.5 %. I changed the behavior of the `ObservableQueue.Clear` method, because I think it should not emit change events if nothing has changed.

Add collection unittests

---

UaClient.UnitTests/UnitTests/DataTypeIdAttributeTests.cs
UaClient.UnitTests/UnitTests/IssuedIdentityTests.cs
UaClient.UnitTests/UnitTests/MonitoredItemAttributeTests.cs
UaClient.UnitTests/UnitTests/UaApplicationOptionsTests.cs
UaClient.UnitTests/UnitTests/UserNameIdentityTests.cs
UaClient.UnitTests/UnitTests/X509IdentityTests.cs
UaClient.UnitTests/UnitTests/XmlEncodingIdAttributeTests.cs

This is mainly to increase the covered file count. For the UaTcpChannelOptions default, I only test for a lower bound. Testing the actual value would be also possible, but I thought that this is to strict.

Add some minor unit tests

---

.github/workflows/unittests.yml
UaClient/Internal/System.Diagnostics.CodeAnalysis.cs
UaClient/ServiceModel/Ua/ExpandedNodeId.cs
UaClient/ServiceModel/Ua/ExtensionObject.cs
UaClient/ServiceModel/Ua/LocalizedText.cs
UaClient/ServiceModel/Ua/NodeId.cs
UaClient/Workstation.UaClient.csproj

While it is possible to use the NRTs with netstandard 2.0, it does not provide the very usefull attributes like `NotNullWhenAttribute`. It seems the only way to get it compile for netstandard 2.0 is to add those attributes to the project. This takes away my enthusiasm a little bit. Nonetheless I think it 'd still be useful to keep on converting the API.

Nullable reference types

---

UaClient.UnitTests/UnitTests/VariantTests.cs
UaClient/ServiceModel/Ua/Variant.cs

Here the NRT raises some interesting questions: is it allowed to pass null values to the different constructor variants like `Variant(string? value)` or should we restrict it to `Variant(string value)`. The first version does not throw an can be serialized. The binary encoder will serialize it as an untyped null value. That's what the reference implementation does as well, so this seems to be correct. But if we should agree on this, shouldn't that also be true for `Variant(int[] value)`? Because here the constructor would throw on `null` values.

[WIP] Add nullable annotation to Variant

---

UaClient/Collections/ErrorsContainer.cs
UaClient/Collections/ObservableQueue.cs
UaClient/ServiceModel/Ua/Channels/CommunicationObject.cs
UaClient/ServiceModel/Ua/Channels/ServiceOperation.cs
UaClient/ServiceModel/Ua/DataValue.cs
UaClient/ServiceModel/Ua/DataValueExtensions.cs
UaClient/ServiceModel/Ua/DiagnosticFlags.cs
UaClient/ServiceModel/Ua/DiagnosticInfo.cs
UaClient/ServiceModel/Ua/DirectoryStore.cs
UaClient/ServiceModel/Ua/EventHelper.cs
UaClient/ServiceModel/Ua/ExpandedNodeId.cs
UaClient/ServiceModel/Ua/QualifiedName.cs
UaClient/ServiceModel/Ua/StatusCode.cs
UaClient/ServiceModel/Ua/VariantExtensions.cs

The most changes here where straight forward. In some cases I had to use the bang operator `!`. Sometimes the compiler is not smart enough (`if (!string.IsNullOrEmpty(nsu))`) or the annotation is not expressive enough ('this.Task.AsyncState') to describe that the object is not null.

More NRT annotiations

---

UaClient/ServiceModel/Ua/StatusCode.cs
UaClient/ServiceModel/Ua/Variant.cs

Readonly structs prevent the compilers to make defensive copys for readonly fields. Although I do not expect any measureable performance benefits for those two data types in real world programs, I think, it denotes their intentention as immutable value types. Note: this is _not_ a breaking change.

Make `Variant` and `StatusCode` readonly structs

---

UaClient/ServiceModel/Ua/Channels/BinaryDecoder.cs
UaClient/ServiceModel/Ua/Channels/BinaryEncoder.cs
UaClient/ServiceModel/Ua/IDecoder.cs
UaClient/ServiceModel/Ua/IEncoder.cs
UaClient/ServiceModel/Ua/Variant.cs

In some cases a malicious server could have caused a null reference exception. This should be now fixed and cause a `ServiceResultException`.

Add nullable reference type annotations for the binary encoding

---

UaClient/ServiceModel/Ua/Channels/BinaryDecoder.cs
UaClient/ServiceModel/Ua/Channels/BinaryEncoder.cs
UaClient/ServiceModel/Ua/Channels/UaTcpMessageTypes.cs
UaClient/ServiceModel/Ua/Channels/UaTcpSecureChannel.cs
UaClient/ServiceModel/Ua/Channels/UaTcpSessionChannel.cs
UaClient/ServiceModel/Ua/Channels/UaTcpTransportChannel.cs
UaClient/ServiceModel/Ua/ServiceResult.cs
UaClient/ServiceModel/Ua/UaApplication.cs

This PR adds nullable annotations to the TCP channels. I had to insert the damnit operator at many places, because there are several variables that are assigned on opening and used later on, but they are null before that. Maybe, there are ways to work around that, but I just wanted to add the annotation and not to change the logic.
One thing that cannot be very well annotated is the nullabillity of properties. While it is very easy to create a response with a response header which is null (e.g.  `new BrowseResponse {}`), the response of an actual service request (e.g. `BrowseAsync(...)`) has always an non-null response header else the method would throw. But there is no way to describe this fact on a language level.

Add nullable reference type annotations to the tcp channels

---

UaClient.UnitTests/UnitTests/ArraySegmentExtensionTests.cs

Note: The CopyTo() method behaves slightly different than its dotnet core counterpart when the destination segment capacity is not large enough. Not a real problem, but something to keep in mind if this implementation is removed in favor of the dotnet core version - in five years or so :).

Add unit tests for the array segment extensions

---

UaClient/ServiceModel/Ua/UaTcpDiscoveryService.cs

The `IDisposable` interface is not used in the entire project. And as far as I have seen, none instance of `UaTcpDiscoverService` is publicly accessable. Hence it should be safe to remove that code.

Remove unused IDisposable implementation of UaTcpDiscoveryService

---

UaClient/ServiceModel/Ua/AttributeServiceSet.cs
UaClient/ServiceModel/Ua/Channels/UaTcpSecureChannel.cs
UaClient/ServiceModel/Ua/MethodServiceSet.cs
UaClient/ServiceModel/Ua/MonitoredItemServiceSet.cs
UaClient/ServiceModel/Ua/NodeManagementServiceSet.cs
UaClient/ServiceModel/Ua/QueryServiceSet.cs
UaClient/ServiceModel/Ua/SessionServiceSet.cs
UaClient/ServiceModel/Ua/SubscriptionServiceSet.cs
UaClient/ServiceModel/Ua/UaTcpDiscoveryService.cs
UaClient/ServiceModel/Ua/ViewServiceSet.cs

This PR adds a link to the corresponding specification section for the service sets.

Add "seealso" reference on the service set specification

---

UaClient/ServiceModel/Ua/Channels/BinaryDecoder.cs
UaClient/ServiceModel/Ua/Channels/BinaryEncoder.cs

This PRs add some documentation to the binary encoder and decoder. The most important point are the `<seealso/>` tags that reference the corresponding specification section.

Add documentation to the binary encoder and decoder

---

UaClient/ServiceModel/Ua/IOptionalFields.cs

The `IOptionalFields` interface formalize the support for optional fields/properties. While it would be possible to implement optional fields in derived class with a naming convention only, having the interface makes it easier to test if the parent class already has optional fields; even over nodeset/assembly boundaries.

Add the IOptionalFields interface

---

UaClient/ServiceModel/Ua/SubscriptionBase.cs

Split MonitoredItemCreateRequest array to chunks of MaxMonitoredItemsPerCall size.
Operation limit of a server, particularly MaxMonitoredItemsPerCall https://reference.opcfoundation.org/v104/Core/docs/Part5/6.3.11/ , does not allow to send all the MonitoredItems defined in SubscriptionBase class in one batch. Chunking the MonitoredItemCreateRequest array allow adding items up to subscription maximum nodes limit.
In my server MaxMonitoredItemsPerCall = 100, subscription maximum nodes limit = 1000. I did not attempt to add additional attribute of  MaxMonitoredItemsPerCall, as i think suggested defaults will work in most cases.

Split MonitoredItemCreateRequest array to chunks

---

UaClient/ServiceModel/Ua/Channels/UaClientConnection.cs
UaClient/ServiceModel/Ua/Channels/UaTcpConnectionProvider.cs
UaClient/ServiceModel/Ua/Channels/UaTcpTransportChannel.cs
UaClient/ServiceModel/Ua/ITransportConnection.cs
UaClient/ServiceModel/Ua/ITransportConnectionProvider.cs
UaClient/ServiceModel/Ua/UaApplicationOptions.cs

Here is the first step to the complete `StackProfile` implementation. In this PR I'm adding the interfaces for the connection part. I tried to introduce it in a very gentle way without breaking changes, yet. But there is one place where this didn't work out. Namely, the `UaTcpTransportChannel.Socket` will always return `null`.
There are some design consideration to be made:
1. `ITransportConnection.SendAsync` takes `(byte[] buffer, int offset, int count, …)` as arguments. There are two possible alternatives: `ArraySegment<byte>` and `Memory<byte>`. I do like having a specialized type to represent the triple. We already use `ArraySegment` in some parts. The more modern choice would be `Memory<byte>`. While we could use the latter, as long as we support  netstandard 2.0, we cannot profit …

StackProfile part 1: Tcp connection provider

---

UaClient.UnitTests/IntegrationTests/IntegrationTests.cs
UaClient.UnitTests/UnitTests/Channels/UaSecureConversationTests.cs
UaClient.UnitTests/UnitTests/UaApplicationOptionsTests.cs
UaClient/ServiceModel/Ua/Channels/ClientSecureChannel.cs
UaClient/ServiceModel/Ua/Channels/ClientSessionChannel.cs
UaClient/ServiceModel/Ua/Channels/ClientTransportChannel.cs
UaClient/ServiceModel/Ua/Channels/MessageTypes.cs
UaClient/ServiceModel/Ua/Channels/StackProfiles.cs
UaClient/ServiceModel/Ua/Channels/UaClientConnection.cs
UaClient/ServiceModel/Ua/Channels/UaSecureConversation.cs
UaClient/ServiceModel/Ua/DiscoveryService.cs
UaClient/ServiceModel/Ua/IConversation.cs
UaClient/ServiceModel/Ua/SubscriptionBase.cs
UaClient/ServiceModel/Ua/TransportConnectionOptions.cs
UaClient/ServiceModel/Ua/UaApplication.cs
UaClient/ServiceModel/Ua/UaApplicationOptions.cs

This is the last PR in this series. One can now inject the stack profile with the channel constructor. As fallback the stack profile will be determine by the `EndpointDescription`. At the moment `StackProfiles.GetStackProfile()` only returns the `TcpUascBinary` stack. Since the channels can now (theoretically) handle other profiles, they are renamed, e.g., `UaTcpXxxChannel` to `ClientXxxChannel`.

StackProfile part 5: The great renaming

---

UaClient.UnitTests/TestCertificateStore.cs
UaClient.UnitTests/ThrowingTestCertificateStore.cs
UaClient.UnitTests/UnitTests/Channels/UaSecureConversationTests.cs
UaClient.UnitTests/UnitTests/ServiceExtensionsTests.cs
UaClient.UnitTests/coverlet.runsettings
UaClient/ServiceModel/Ua/Channels/ClientSecureChannel.cs
UaClient/ServiceModel/Ua/Channels/ClientSessionChannel.cs
UaClient/ServiceModel/Ua/Channels/ClientTransportChannel.cs
UaClient/ServiceModel/Ua/Channels/UaSecureConversation.cs
UaClient/ServiceModel/Ua/Channels/UaSecureConversationProvider.cs
UaClient/ServiceModel/Ua/Channels/UaTcpConnectionProvider.cs
UaClient/ServiceModel/Ua/DirectoryStore.cs
UaClient/ServiceModel/Ua/ICertificateStore.cs
UaClient/ServiceModel/Ua/IConversationProvider.cs
UaClient/ServiceModel/Ua/ITransportConnectionProvider.cs
UaClient/ServiceModel/Ua/ServiceExtensions.cs

In the last PR, I said it would be the last one in this series. But I forgot one important point. The factory methods (`IConversationProvider.CreateAsync` and `ITransportConnectionProvider.ConnectAsync`) should take a cancellation token as argument.

StackProfile part 6: Addendum

---

UaClient/ServiceModel/Ua/Channels/ClientSessionChannel.cs

When connecting to a server that has no certificate, ClientSessionChannel.OnOpenAsync throws an exception because it tries to read a certificate from an byte array that is null.
This PR ensures that we only read the certificate if the byte array is not null.
Fixes issue #246

Prevent exception when ServerCertificate is null

---

UaClient/ServiceModel/Ua/Channels/ClientSecureChannel.cs
UaClient/ServiceModel/Ua/Channels/CommunicationObject.cs

Fixes https://github.com/convertersystems/opc-ua-client/issues/236
The only question for me is should we leave the _exception list filled with the exception or can we consume it.

forward internal errors instead of timeout status codes

---

UaClient/ServiceModel/Ua/Channels/BinaryDecoder.cs
UaClient/ServiceModel/Ua/Channels/BinaryEncoder.cs
UaClient/ServiceModel/Ua/Channels/ClientSecureChannel.cs
UaClient/ServiceModel/Ua/Channels/ClientSessionChannel.cs
UaClient/ServiceModel/Ua/Channels/ClientTransportChannel.cs
UaClient/ServiceModel/Ua/Channels/CommunicationObject.cs
UaClient/ServiceModel/Ua/Channels/UaSecureConversation.cs
UaClient/ServiceModel/Ua/Channels/UaTcpConnectionProvider.cs
UaClient/ServiceModel/Ua/DiscoveryService.cs

Disposes DiscoveryService, semaphores, streams, tcpclients, empties queues.
After OpcClient has been faulted, then AbortASync should be called then Dispose on the object.

Recreating and reconnecting ClientSessionChannel caused memory leaks. Implement IDisposable on all underlying objects.

---

UaClient/ServiceModel/Ua/Channels/ClientSecureChannel.cs
UaClient/ServiceModel/Ua/Channels/ClientSessionChannel.cs
UaClient/ServiceModel/Ua/Channels/UaClientConnection.cs
UaClient/ServiceModel/Ua/Channels/UaSecureConversation.cs
UaClient/ServiceModel/Ua/DirectoryStore.cs
UaClient/ServiceModel/Ua/ServiceExtensions.cs
UaClient/ServiceModel/Ua/SubscriptionBase.cs

Various `await` statements did not explicitly specify `ConfigureAwait`. This PR adds `.ConfigureAwait(false)` to all `await` calls where no awaiter behaviour was specified.
The [Microsoft.VisualStudio.Threading.Analyzers](https://www.nuget.org/packages/Microsoft.VisualStudio.Threading.Analyzers) package was used to detect the `await` statements that did not explicitly configure the awaiter behaviour.

Add missing ConfigureAwait calls
